<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use App\Models\User;
use App\Models\QuoteRequest;


class CreateQuoteRequestTest extends TestCase
{
    /**
     * A basic feature test example.
     */
    public function test_example(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }


    use RefreshDatabase;

    public function test_create_quote_request(): void
    {
        // Create user to get a slug, in this case we define it as printer-tester1, but it could have been generated by the factory if i had defined the name instead
        $user = User::factory()->create([
            'slug' => 'printer-tester1'
        ]);


        // Defining the payload/request body 
        $payload = [
            'slug' => $user->slug,
            'customer_name' => 'Cliente Bruno',
            'customer_email' => 'bruno@teste.com',
            'title' => 'Suporte para câmara',
            'description' => 'Preciso de um suporte para GoPro',
            'quantity' => 1
        ];

        // Posting QuoteRequest and storing response
        $response = $this->postJson('/api/quote-requests', $payload);

        // Asserting response status as 201 (created)
        $response->assertStatus(201);

        // Asserting that the payload exists now in the database, after creation
        $this->assertDatabaseHas('quote_requests', [
            'user_id' => $user->id,
            'customer_name' => 'Cliente Bruno',
            'customer_email' => 'bruno@teste.com',
            'title' => 'Suporte para câmara',
            'description' => 'Preciso de um suporte para GoPro',
            'quantity' => 1
        ]);

        $this->assertEquals(1, QuoteRequest::count()); // Asserts that only 1 record exists
    }

    public function test_create_quote_request_with_missing_fields(): void
    {
        // Creating user like before
        $user = User::factory()->create([
            'slug' => 'printer-tester1'
        ]);

        // Defining payload, with missing fields
        $payload = [
            'slug' => $user->slug,
            // 'customer_name' => 'Cliente Bruno',
            // 'customer_email' => 'bruno@teste.com',
            //'title' => 'Suporte para câmara',
            'description' => 'Preciso de um suporte para GoPro',
            'quantity' => 1
        ];

        // Posting QuoteRequest and storing response
        $response = $this->postJson('/api/quote-requests', $payload);

        // Asserting response status as 422 (Unprocessable Entity), fails due to validation errors
        $response->assertStatus(422);
    }
}
